name: string-function
on: push

jobs:
  string-function:
    runs-on: ubuntu-latest
    steps:
      - name: startsWith
        # pass
        if: startsWith('github actions','git')
        run: echo "startsWith git"
      - name: startsWith
        # fail
        if: startsWith('github actions','test')
        run: echo "startsWith test"

      - name: endsWith
        # pass
        if: endsWith('github actions','ions')
        run: echo "endsWith ions"
      - name: endsWith
        # fail
        if: endsWith('github actions','test')
        run: echo "endsWith test"

      - name: contains
        # pass
        if: contains('github actions','act')
        run: echo "contains act"
      - name: contains
        # pass
        # , 로 배열 아이템 구분
        if: contains('github, actions','git')
        run: echo "contains test"
