name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        # 첫 번째 스텝에서는 PAT를 받아와서 로그인을 한다.
        # 깃허브 액션 job에서 권한을 사용할 수 있게 된다.
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo
        # 입력받은 inputs 값으로 레포를 만든다.
        run: |
          gh repo create seongjun-actions/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
